// Generated by Selenium IDE
const { Builder, By, Capabilities, until, Key} = require('selenium-webdriver')
const assert = require('assert')
// const caps = new Capabilities();
// caps.setPageLoadStrategy("none");
//

describe('ducks tests', function() {

    this.timeout(300000)
    let driver
    let vars
    let getAllWindowHandles
    const password = "3hJ!u2KX^7"

    before(async function() {
        driver = await new Builder()
            // .withCapabilities(caps)
            .forBrowser('chrome')
            .build()
        vars = {}

        await driver.get("https://wavesducks.com/")
        await driver.manage().window().setRect({ width: 1440, height: 900 })
        await driver.executeScript("window.open('https://waves.exchange/sign-up/', '_blank');")
        getAllWindowHandles = await driver.getAllWindowHandles()
        await driver.sleep(5000)
        await driver.switchTo().window(getAllWindowHandles[1])
    })

    it('registration', async function() {
        await driver.findElement(By.css(".css-v28l6")).click()
        await driver.sleep(3000)
        await driver.findElement(By.css(".css-roynbj .css-15q5r51:nth-child(1) .css-1o78ni4")).sendKeys(password)
        await driver.sleep(100)
        await driver.findElement(By.css(".css-roynbj .css-15q5r51:nth-child(2) .css-1o78ni4")).sendKeys(password)
        await driver.sleep(100)
        await driver.findElement(By.css(".css-g013ys")).click()
        await driver.sleep(400)
        await driver.findElement(By.css(".css-hw3m92")).click()
        await driver.sleep(2000)
        const address = await driver.findElement(By.css(".css-13ngssx")).getText()
        await driver.findElement(By.css(".css-9ctqy3")).click()
        await driver.findElement(By.css(".css-1s7zn1r")).sendKeys(address)
        await driver.findElement(By.css(".css-10j114y")).click()
    })

    it('authorization', async function() {
        await driver.switchTo().window(getAllWindowHandles[0])
        await driver.sleep(2000)
        await driver.findElement(By.linkText("Marketplace")).click()
        await driver.sleep(2000)
        await driver.findElement(By.css(".header-menu-items > .header-menu-item:nth-child(1)")).click()
        await driver.sleep(2000)
        await driver.findElement(By.css(".login-page__authorization_method_first_line")).click()
        await driver.sleep(2000)
        await driver.switchTo().frame(2)
        await driver.sleep(2000)
        await driver.findElement(By.css(".css-1wyiskf")).sendKeys(password)
        await driver.sleep(2000)
        await driver.findElement(By.css(".css-14ilpg8")).click()
        await driver.sleep(2000)
    })

    it('ui test', async function() {
        await driver.findElement(By.css(".icon-magnifier")).click()
        await driver.sleep(2000)
        await driver.findElement(By.css(".form-control")).sendKeys("123456")
        await driver.sleep(2000)
        await driver.findElement(By.css(".form-control")).sendKeys(Key.ENTER)
        await driver.sleep(2000)
        await driver.findElement(By.css(".header-menu-items > .header-menu-item:nth-child(1)")).click()
        await driver.findElement(By.css(".header-menu-items > .header-menu-item:nth-child(2)")).click()
        await driver.sleep(2000)
        await driver.findElement(By.css(".header-menu-items > .header-menu-item:nth-child(3)")).click()
        await driver.sleep(2000)
        await driver.findElement(By.css(".header-menu-items > .header-menu-item:nth-child(4)")).click()
        await driver.sleep(2000)
    })

})
